# appveyor.yml Reference
# https://www.appveyor.com/docs/appveyor-yml/
#
# How to use AppVeyor to build a multi-arch Docker image for Linux and Windows
# https://stefanscherer.github.io/use-appveyor-to-build-multi-arch-docker-image/
#
# Building ASP.NET Core apps on both Windows and Linux using AppVeyor
# https://andrewlock.net/building-asp-net-core-apps-on-both-windows-and-linux-using-appveyor/
#
# appveyor.yml Example:
# https://github.com/cdcseacave/openMVS/blob/master/.appveyor.yml

version: '{build}'
image:
  - Ubuntu2004
  - Visual Studio 2017
build: false
clone_depth: 50
branches:
  except:
    - gh-pages

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  MAVEN_OPTS: "-Xmx768m -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2"
  JAVA_OPTS: "-Xmx768m"

for:
  -
    #------------------
    # Ubuntu
    #------------------
    matrix:
      only:
        - image: Ubuntu2004

    install:
      - git submodule update --init
    test_script:
      - scripts/integration_test

    after_test:
      # remove self maven install
      # - rm -rf $HOME/.m2/repository/$project_gid_aid_path
      # remove maven install file
      - rm -rf $HOME/.m2/wrapper/dists/*/*/*.zip
      # remove gradle install file
      # - rm -rf $HOME/.gradle/wrapper/dists/*/*/*.zip
      # # remove sdkman install file
      - rm -rf $HOME/.sdkman/archives/*

    cache:
      # if cache size is exceed appveyor limit:
      #   Compressed cache item cannot exceed 1,048,576,000 bytes
      # skip below maven cache:
      - $HOME/.m2/
      - $HOME/.gradle/
      - $HOME/.sdkman/
  -
    #------------------
    # Windows
    #------------------
    matrix:
      only:
        - image: Visual Studio 2017
    install:
      - ps: "ls 'C:/Program Files/Java/jdk*'"
      - ps: "ls 'C:/Program Files (x86)/Java/jdk*'"
      - echo JAVA_HOME=%JAVA_HOME%, HOMEPATH=%HOMEPATH%, PATH=%PATH%

    test_script:
      # test under java 11
      - set JAVA_HOME=C:\Program Files\Java\jdk11
      - ./mvnw.cmd -DperformRelease -P!gen-sign -V --no-transfer-progress clean install
      # test under java 8
      - set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
      - ./mvnw.cmd -DperformRelease -P!gen-sign -V --no-transfer-progress surefire:test

    after_test:
      # remove self maven install
      # - ps: Remove-Item -r -fo $home\.m2\repository\$project_gid_aid_path
      # remove maven install file
      - ps: Remove-Item -Path $HOME\.m2\wrapper\dists\*\*\*.zip

    cache:
      # https://www.appveyor.com/docs/build-cache/
      - '%HOMEDRIVE%%HOMEPATH%\.m2\'
